# Generated by Django 4.0.5 on 2022-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_full_content_alter_new_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='show_in_home',
            field=models.BooleanField(default=False, verbose_name='Show in home'),
        ),
    ]
