# Generated by Django 4.0.5 on 2022-06-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name_category')),
                ('image', models.ImageField(upload_to='category/', verbose_name='Image')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_deleted')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name_product')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Image')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('content', models.TextField(max_length=1000, verbose_name='Content')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_deleted')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
