# Generated by Django 4.0.5 on 2022-07-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
    ]
