# Generated by Django 4.0.5 on 2022-07-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_parent_category_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ManyToManyField(default=None, null=True, to='services.promotion', verbose_name='Promotion'),
        ),
    ]
