# Generated by Django 4.0.5 on 2022-07-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_product_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ManyToManyField(default=None, to='services.promotion', verbose_name='Promotion'),
        ),
    ]
