# Generated by Django 4.0.5 on 2022-06-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Moderation'), (2, 'Rejected'), (3, 'Published')], default=1, verbose_name='Status'),
        ),
    ]
