# Generated by Django 4.0.5 on 2022-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Title new')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Image')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is_deleted')),
                ('show_in_home', models.BooleanField(default=False, verbose_name='Show in home')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
