# Generated by Django 4.0.5 on 2022-06-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('url', models.CharField(max_length=100, verbose_name='Link URL')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='Show in footer')),
                ('login_required', models.BooleanField(default=False, verbose_name='Login required')),
                ('anonymous_only', models.BooleanField(default=False, verbose_name='anonymous_only')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
            },
        ),
    ]
