# Generated by Django 4.0.5 on 2022-07-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is_deleted'),
        ),
    ]
